repository:
    # See https://developer.github.com/v3/repos/#edit for all available settings.

    # Either `true` to make the repository private, or `false` to make it public.
    private: true

    # Either `true` to enable issues for this repository, `false` to disable them.
    has_issues: false

    # Either `true` to enable the wiki for this repository, `false` to disable it.
    has_wiki: false

    # Either `true` to enable downloads for this repository, `false` to disable them.
    has_downloads: false

    # Updates the default branch for this repository.
    default_branch: dev

    # Either `true` to allow squash-merging pull requests, or `false` to prevent
    # squash-merging.
    allow_squash_merge: true

    # Either `true` to allow merging pull requests with a merge commit, or `false`
    # to prevent merging pull requests with merge commits.
    allow_merge_commit: false

    # Either `true` to allow rebase-merging pull requests, or `false` to prevent
    # rebase-merging.
    allow_rebase_merge: false

# Labels: define labels for Issues and Pull Requests
labels:
    - name: 'Type: Bug'
      color: e80c0c
      description: Something isn't working as expected.

    - name: 'Type: Enhancement'
      color: 54b2ff
      description: Suggest an improvement for an existing feature.

    - name: 'Type: Feature'
      color: 54b2ff
      description: Suggest a new feature.

    - name: 'Type: Security'
      color: fbff00
      description: A problem or enhancement related to a security issue.

    - name: 'Type: Question'
      color: 9309ab
      description: Request for information.

    - name: 'Type: Test'
      color: ce54e3
      description: A problem or enhancement related to a test.

    - name: 'Status: Awaiting Review'
      color: 24d15d
      description: Ready for review.

    - name: 'Status: WIP'
      color: 07b340
      description: Currently being worked on.

    - name: 'Status: Waiting'
      color: 38C968
      description: Waiting on something else to be ready.

    - name: 'Status: Stale'
      color: 66b38a
      description: Has had no activity for some time.

    - name: 'Duplicate'
      color: EB862D
      description: Duplicate of another issue.

    - name: 'Invalid'
      color: faef50
      description: This issue doesn't seem right.

    - name: 'Priority: High +'
      color: ff008c
      description: Task is considered higher-priority.

    - name: 'Priority: Low -'
      color: 690a34
      description: Task is considered lower-priority.

    - name: 'Documentation'
      color: 2fbceb
      description: An issue/change with the documentation.

    - name: "Won't fix"
      color: C8D9E6
      description: Reported issue is working as intended.

    - name: '3rd party issue'
      color: e88707
      description: This issue might be caused by a 3rd party script/package/other reasons

    - name: 'Os: Windows'
      color: AEB1C2
      description: Is Windows-specific

    - name: 'Os: Mac'
      color: AEB1C2
      description: Is Mac-specific

    - name: 'Os: Linux'
      color: AEB1C2
      description: Is Linux-specific
